version: '3.3'

services:
  nuxt:
    build:
      context: .
    image: nuxt_dev
    container_name: nuxt_dev
    ports:
      - '3000:3000'
    environment:
      - NUXT_PUBLIC_VUEFIRE_API_KEY=''
      - NUXT_PUBLIC_VUEFIRE_AUTH_DOMAIN=''
      - NUXT_PUBLIC_VUEFIRE_PROJECT_ID=''
      - NUXT_PUBLIC_VUEFIRE_APP_ID=''
      - NUXT_API_SECRET=api_secret_token
      - NUXT_PUBLIC_API_BASE=public_token
